:verbose: false
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20

:queues:
  - critical
  - default
  - low
  - event
  - [active_storage_analysis, 3]
  - [active_storage_purge, 1]